<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEarch_Arrow</name>
   <tag></tag>
   <elementGuidId>9119aa80-fa4e-4dee-a523-5f5866801b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id=&quot;LU_QBC_QB_COND_SECTION_1_ROW_6_DATATEXTFIELD&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
