<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Analysis_Defination_Icon</name>
   <tag></tag>
   <elementGuidId>17e1c662-7c14-4e20-b08b-6dc4bc1439fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;HBar_Applications_T1G3I2&quot;]//span[@class=&quot;dxr-lblText&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
