<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toggle_Approve_Donor_Name</name>
   <tag></tag>
   <elementGuidId>eb8a9635-e70c-4d64-a676-65587934ef0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;HeaderBar1Left_Workfow_MENUDATA_JsContainer&quot;]//tr[@id=&quot;ACH_MBR_Can_See_Contact_Names&quot;]//td[@id=&quot;ACH_MBI_C2_Can_See_Contact_Names&quot;]
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
