<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manage_Studeis_Icon</name>
   <tag></tag>
   <elementGuidId>6e223dba-49c3-4625-a871-8050ec7720a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id=&quot;HBar_Applications_T0G2I1&quot;]//span[@class=&quot;dxr-lblText&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
