<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Active_Consent_Maintenance</name>
   <tag></tag>
   <elementGuidId>5daeaefb-9716-46fe-8fa4-9d2c5790f972</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id=&quot;HeaderBar1Left_Workfow_MENUDATA&quot;]//td[@id=&quot;ACH_MBI_C2_Consent_Maintenance_Update_Status_to_Active&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
