<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get_value_Sub_location_type</name>
   <tag></tag>
   <elementGuidId>62ac95ef-bbaf-4556-9a14-8a26aca3b808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id=&quot;aLayoutRootTable&quot;]//input[@id=&quot;SUBLOCATIONTYPE_SUBLOCATIONTYPE_I&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
