<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>General_Administartion_Icon</name>
   <tag></tag>
   <elementGuidId>981edad4-4255-4fae-8474-8325b1f97247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;HBar_Applications_T1G3_EBTN&quot;]//span[@class=&quot;dxr-lblText&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
