<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Column_value</name>
   <tag></tag>
   <elementGuidId>ce93e82f-cb86-466a-ac10-36a28da00f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;QBColPickerBox&quot;]//option[@value=&quot;de2b8502-bcc1-476a-930d-89c0d253b55a&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
