<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Admin_Icon</name>
   <tag></tag>
   <elementGuidId>dfe992c7-6518-4c6f-9f34-0a64f67b30e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;dxtc-vp&quot;]//li[@id=&quot;HBar_Applications_TC_T2&quot;]//span[text()=&quot;Admin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
