<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Project_Team</name>
   <tag></tag>
   <elementGuidId>131fcc04-44c4-4daf-9640-5a4e6bc2cd0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AchieverWFDataListAuto_dxdt0_AchieverWFDataListAuto_DetailTabs_0_T1T']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
